# Generated by Django 2.1.7 on 2019-05-16 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('text', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fragment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('translated', models.TextField()),
                ('value', models.FloatField(default=0)),
                ('state', models.CharField(choices=[('1', 'To translate'), ('2', 'Translating'), ('3', 'To review'), ('4', 'Reviewing'), ('5', 'To finish'), ('6', 'Finished')], default='1', max_length=12)),
                ('total_reviews', models.IntegerField(default=0)),
                ('translator', models.IntegerField(blank=True, null=True)),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='text.Text')),
            ],
        ),
    ]
