# Generated by Django 2.1.7 on 2019-05-15 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fragment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('value', models.FloatField(default=0)),
                ('state', models.CharField(choices=[('1', 'To translate'), ('2', 'Translating'), ('3', 'To review'), ('4', 'Reviewing'), ('5', 'To finish'), ('6', 'Finished')], default='1', max_length=12)),
                ('total_reviews', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(max_length=200)),
                ('total_fragments', models.IntegerField(default=0)),
                ('finished_fragments', models.IntegerField(default=0)),
                ('author', models.IntegerField()),
                ('language', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='fragment',
            name='text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='text.Text'),
        ),
    ]
