# Generated by Django 2.1.7 on 2019-05-16 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(max_length=200)),
                ('total_fragments', models.IntegerField(default=0)),
                ('finished_fragments', models.IntegerField(default=0)),
                ('author', models.IntegerField()),
                ('language', models.IntegerField()),
                ('category', models.ManyToManyField(to='category.Category')),
            ],
        ),
    ]
