# Generated by Django 2.1.7 on 2019-05-20 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fragment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('value', models.FloatField(default=0)),
                ('state', models.CharField(choices=[('1', 'To translate'), ('2', 'Translating'), ('3', 'To review'), ('4', 'Reviewing'), ('5', 'To finish'), ('6', 'Finished')], default='1', max_length=12)),
                ('total_reviews', models.IntegerField(default=0)),
                ('id_author', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='text',
            name='content',
        ),
        migrations.AddField(
            model_name='text',
            name='context',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='text',
            name='finished_fragments',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='text',
            name='language',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='text',
            name='total_fragments',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='text',
            name='author',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='fragment',
            name='id_text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='text.Text'),
        ),
    ]
