# Generated by Django 2.1.7 on 2019-05-20 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0002_auto_20190520_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fragment',
            name='id_author',
            field=models.IntegerField(null=True),
        ),
    ]
