# Generated by Django 2.1.7 on 2019-05-21 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0003_auto_20190520_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='fragment',
            name='id_translator',
            field=models.IntegerField(null=True),
        ),
    ]
